const koreanFeastFor2Modifiers = {
  "White Rice": "- WHITE RICE (1LB)",
  "Purple Rice": "- PURPLE RICE (1LB)",
  Noodles: "- NOODLES (1LB)",
  Salad: "- SALAD (8oz)",
  Beef: "- BEEF (10oz)",
  Chicken: "- CHICKEN (10oz)",
  "Spicy Pork": "- SPICY PORK (10oz)",
  Tofu: "- TOFU (10oz)",
  Cucumbers: "- CUCUMBERS (5oz)",
  Corn: "- CORN (5oz)",
  "Korean Radish": "- KOREAN RADISH (5oz)",
  Carrots: "- CARROTS (5oz)",
  "Bean Sprouts": "- BEAN SPROUTS (5oz)",
  Kimchi: "- KIMCHI (5oz)",
  Kale: "- KALE (5oz)",
  Scallions: "- SCALLIONS (EGG CUP)",
  Cilantro: "- CILANTRO (EGG CUP)",
  "Crispy Garlic": "- CRISPY GARLIC (SAUCE CUP)",
  "Sesame Seeds": "- SESAME SEEDS (SAUCE CUP)",
};

const koreanFeastFor4Modifiers = {
  "White Rice": "- WHITE RICE (1LB)",
  "Purple Rice": "- PURPLE RICE (1LB)",
  Noodles: "- NOODLES (1LB)",
  Salad: "- SALAD (8oz)",
  Beef: "- BEEF (10oz)",
  Chicken: "- CHICKEN (10oz)",
  "Spicy Pork": "- SPICY PORK (10oz)",
  Tofu: "- TOFU (10oz)",
  Cucumbers: "- CUCUMBERS (5oz)",
  Corn: "- CORN (5oz)",
  "Korean Radish": "- KOREAN RADISH (5oz)",
  Carrots: "- CARROTS (5oz)",
  "Bean Sprouts": "- BEAN SPROUTS (5oz)",
  Kimchi: "- KIMCHI (5oz)",
  Kale: "- KALE (5oz)",
  Scallions: "- SCALLIONS (EGG CUP)",
  Cilantro: "- CILANTRO (EGG CUP)",
  "Crispy Garlic": "- CRISPY GARLIC (SAUCE CUP)",
  "Sesame Seeds": "- SESAME SEEDS (SAUCE CUP)",
};

module.exports = { koreanFeastFor2Modifiers, koreanFeastFor4Modifiers };
